version: '3.8'

services:
  multi-restaurant-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: multi-restaurant-platform-backend
    container_name: multi-restaurant-platform
    ports:
      - "8081:8080" # HOST_PORT:CONTAINER_PORT - Access on Mac via 8081, app in container runs on 8080
    environment:
      - SERVER_PORT=8080 # Spring Boot app inside container will listen on port 8080
      # - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped