-- Flyway migration script V1

-- Create the users table based on User entity and BaseEntity
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL, -- Ensure sufficient length for hashed passwords
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
    -- Add other user fields here if defined in the entity (e.g., first_name, is_active)
    -- first_name VARCHAR(50),
    -- last_name VARCHAR(50),
    -- is_active BOOLEAN DEFAULT true NOT NULL
);

-- Create the user_roles join table for the @ElementCollection mapping
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL, -- Matches EnumType.STRING
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    -- Create a composite primary key to ensure unique user-role combinations
    PRIMARY KEY (user_id, role)
);

-- Optional: Add indexes for performance on frequently queried columns
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_email ON users (email);