-- File: backend/api/src/main/resources/db/migration/V2__Create_Restaurant_Tables.sql

-- Create the restaurants table
CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_restaurants_name UNIQUE (name), -- Ensure restaurant names are unique
    CONSTRAINT uq_restaurants_email UNIQUE (email) -- Ensure restaurant emails are unique if provided
);

-- Create the restaurant_admins join table for the ManyToMany relationship
-- between restaurants and users (administrators)
CREATE TABLE restaurant_admins (
    restaurant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_restaurant_admins PRIMARY KEY (restaurant_id, user_id),
    CONSTRAINT fk_restaurant_admins_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
    CONSTRAINT fk_restaurant_admins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Optional: Add indexes for performance
CREATE INDEX idx_restaurants_name ON restaurants (name);
CREATE INDEX idx_restaurants_is_active ON restaurants (is_active);
