-- Flyway migration script V3__Create_Menu_Table.sql

-- Create the menus table
CREATE TABLE menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    restaurant_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_menus_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
    CONSTRAINT uq_menus_restaurant_id_name UNIQUE (restaurant_id, name) -- A restaurant cannot have two menus with the same name
);

-- Optional: Add indexes for performance
CREATE INDEX idx_menus_restaurant_id ON menus (restaurant_id);
CREATE INDEX idx_menus_name ON menus (name);
CREATE INDEX idx_menus_is_active ON menus (is_active);

