package com.multirestaurantplatform.security.dto;

import lombok.Data;
import lombok.NonNull; // Or use constructor-based injection if preferred over @NonNull on field

@Data // Lombok: Generates getters, setters, toString, equals, hashCode.
public class JwtAuthenticationResponse {

    @NonNull // Ensures token is not null when using the constructor generated by @Data or if a @RequiredArgsConstructor is used.
    private String accessToken;
    private String tokenType = "Bearer"; // Standard token type

    // Constructor
    public JwtAuthenticationResponse(String accessToken) {
        this.accessToken = accessToken;
    }

    // If you want to include more user details in the response (optional):
    // private String username;
    // private java.util.Collection<? extends org.springframework.security.core.GrantedAuthority> authorities;
    // public JwtAuthenticationResponse(String accessToken, String username, java.util.Collection<? extends org.springframework.security.core.GrantedAuthority> authorities) {
    //     this.accessToken = accessToken;
    //     this.username = username;
    //     this.authorities = authorities;
    // }
}
